"use client";

import { useEffect, useState } from "react";
import type { Filters, Listing, Location } from "@/lib/aqar";
import { CATEGORIES, ROOM_TYPES } from "@/lib/aqar";

const defaults: Filters = { propertyType:"عمارة",purpose:"sale",locations:[{city:"الدمام",neighborhoods:[]},{city:"الخبر",neighborhoods:["الثقبة"]},{city:"الظهران",neighborhoods:[]}],keywords:[],mode:"near",maxPages:2,maxListings:40,priceMin:0,priceMax:2500000,yieldMin:9,minMeters:10,minCount:0,minFloors:0,minStreet:15,areaMin:0,areaMax:0,minDensity:0,sqmMin:0,sqmMax:0 };
const nums: {key:keyof Filters;label:string;hint?:string}[] = [
  {key:"priceMin",label:"السعر من"},{key:"priceMax",label:"السعر إلى"},{key:"yieldMin",label:"أقل عائد فعلي %"},
  {key:"minMeters",label:"أقل عدادات"},{key:"minCount",label:"أقل شقق / غرف"},{key:"minFloors",label:"أقل أدوار"},
  {key:"minStreet",label:"أقل عرض شارع"},{key:"areaMin",label:"المساحة من"},{key:"areaMax",label:"المساحة إلى"},
  {key:"minDensity",label:"شقق لكل 100م²"},{key:"sqmMin",label:"سعر متر الأرض من"},{key:"sqmMax",label:"سعر متر الأرض إلى"},
];
type SavedSet={id:number;name:string;propertyType:string;createdAt:string;count:number;resultsJson:string};
type Profile={id:number;name:string;filtersJson:string};
type SearchSource={category:string;city:string;neighborhood:string;page:number};
const fmt=(v:number|null,d=0)=>v==null?"غير مذكور":new Intl.NumberFormat("ar-SA",{maximumFractionDigits:d}).format(v);
const inputNumber=(value:unknown)=>Number(value)||0;
function deviceHeaders(json=false){let id=localStorage.getItem("aqar-device-id");if(!id){id=crypto.randomUUID();localStorage.setItem("aqar-device-id",id)}return {"x-aqar-device-id":id,...(json?{"content-type":"application/json"}:{})}}

export default function Home(){
  const [filters,setFilters]=useState<Filters>(defaults),[results,setResults]=useState<Listing[]>([]),[busy,setBusy]=useState(false);
  const [message,setMessage]=useState("عدّل المواصفات ثم اضغط «ابدأ البحث»"),[progress,setProgress]=useState(0),[warnings,setWarnings]=useState<string[]>([]);
  const [tab,setTab]=useState<"search"|"saved">("search"),[sets,setSets]=useState<SavedSet[]>([]),[profiles,setProfiles]=useState<Profile[]>([]);
  useEffect(()=>{const timer=setTimeout(()=>{try{const x=localStorage.getItem("aqar-last-filters");if(x)setFilters({...defaults,...JSON.parse(x)})}catch{/* تجاهل بيانات محلية تالفة */}void loadProfiles()},0);return()=>clearTimeout(timer)},[]);
  const countLabel=ROOM_TYPES.has(filters.propertyType)?"أقل غرف (مع المجلس والمقلط)":"أقل شقق";
  function update<K extends keyof Filters>(key:K,value:Filters[K]){setFilters(f=>({...f,[key]:value}))}
  function addLocation(){update("locations",[...filters.locations,{city:"",neighborhoods:[]}])}
  function changeLocation(i:number,key:"city"|"neighborhoods",value:string){const next=filters.locations.map((l,j)=>j===i?{...l,[key]:key==="neighborhoods"?value.split(/[،,]/).map(x=>x.trim()).filter(Boolean):value}:l);update("locations",next as Location[])}
  function clearFields(){setFilters({...defaults,locations:[{city:"",neighborhoods:[]}],priceMax:0,yieldMin:0,minMeters:0,minStreet:0});setResults([]);setMessage("تم مسح حقول البحث.")}
  async function loadProfiles(){try{const r=await fetch("/api/profiles",{headers:deviceHeaders()});const data=await r.json() as {profiles:Profile[]};if(r.ok)setProfiles(data.profiles)}catch{/* يعمل البحث حتى لو تعذر التخزين */}}
  async function saveProfile(){const name=prompt("اسم مواصفات البحث:");if(!name)return;const r=await fetch("/api/profiles",{method:"POST",headers:deviceHeaders(true),body:JSON.stringify({name,filters})});if(r.ok){await loadProfiles();setMessage("حُفظت مواصفات البحث.")}else setMessage("تعذر حفظ المواصفات.")}
  function loadProfile(id:string){const p=profiles.find(x=>x.id===Number(id));if(p){setFilters({...defaults,...JSON.parse(p.filtersJson)});setMessage(`تم تحميل: ${p.name}`)}}
  async function search(){
    const clean={...filters,locations:filters.locations.filter(l=>l.city.trim()),maxPages:Math.min(25,Math.max(1,filters.maxPages)),maxListings:Math.min(500,Math.max(5,filters.maxListings))};
    if(!clean.locations.length){setMessage("أضف مدينة واحدة على الأقل.");return} localStorage.setItem("aqar-last-filters",JSON.stringify(clean));setBusy(true);setResults([]);setWarnings([]);setProgress(0);
    const found=new Map<string,Listing>();let discovered=0;const allSources=(()=>{const a:SearchSource[]=[];for(const category of CATEGORIES[clean.propertyType]?.[clean.purpose]||[])for(const l of clean.locations)for(const neighborhood of(l.neighborhoods.length?l.neighborhoods:[""]))for(let page=1;page<=clean.maxPages;page++)a.push({category,city:l.city,neighborhood,page});return a})();
    for(let i=0;i<allSources.length&&found.size<clean.maxListings;i++){
      const s=allSources[i];setMessage(`قراءة ${s.city}${s.neighborhood?` — ${s.neighborhood}`:""}، صفحة ${s.page}…`);setProgress(Math.round(i/allSources.length*100));
      try{const r=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filters:clean,...s,remaining:Math.min(20,clean.maxListings-found.size)})});const data=await r.json() as {error?:string;discovered?:number;results?:Listing[];warnings?:string[]};if(!r.ok)throw new Error(data.error||"تعذر البحث");discovered+=data.discovered||0;for(const item of data.results||[])found.set(item.listingId,item);if(data.warnings?.length)setWarnings(w=>[...w,...data.warnings!].slice(-20));setResults([...found.values()].sort((a,b)=>b.score-a.score||(b.yieldPct||0)-(a.yieldPct||0)));}catch(e){const m=e instanceof Error?e.message:"تعذر البحث";setWarnings(w=>[...w,m]);if(/429|منع|تحقق|تسجيل دخول/.test(m))break}
    }
    setProgress(100);setBusy(false);setMessage(`اكتمل البحث: اكتُشف ${discovered} رابطًا، وظهرت ${found.size} نتيجة بعد التصفية.`);
  }
  function exportCsv(){if(!results.length)return;const fields:[keyof Listing,string][]=[["listingId","رقم الإعلان"],["status","الحالة"],["propertyType","نوع العقار"],["age","العمر"],["city","المدينة"],["neighborhood","الحي"],["price","السعر"],["sqmPrice","سعر متر الأرض"],["income","الدخل السنوي"],["yieldPct","العائد %"],["area","المساحة"],[ROOM_TYPES.has(filters.propertyType)?"rooms":"apartments",ROOM_TYPES.has(filters.propertyType)?"الغرف مع المجلس والمقلط":"الشقق"],["meters","العدادات"],["floors","الأدوار"],["street","عرض الشارع"],["density","الكثافة"],["url","الرابط"]];const csv="\ufeff"+[fields.map(x=>x[1]),...results.map(r=>fields.map(([k])=>String(r[k]??"")))].map(row=>row.map(x=>`"${x.replace(/"/g,'""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`نتائج-${filters.propertyType}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
  async function saveResults(){if(!results.length){setMessage("لا توجد نتائج لحفظها.");return}const r=await fetch("/api/saved-results",{method:"POST",headers:deviceHeaders(true),body:JSON.stringify({propertyType:filters.propertyType,results})});const d=await r.json() as {set?:{name:string};error?:string};setMessage(r.ok?`حُفظت المجموعة: ${d.set?.name}`:d.error||"تعذر الحفظ")}
  async function loadSets(){const r=await fetch("/api/saved-results",{headers:deviceHeaders()});const data=await r.json() as {sets:SavedSet[]};if(r.ok)setSets(data.sets);setTab("saved")}
  async function deleteSet(id:number){if(!confirm("هل تريد حذف هذه المجموعة المحفوظة؟"))return;await fetch(`/api/saved-results?id=${id}`,{method:"DELETE",headers:deviceHeaders()});await loadSets()}
  function openSet(s:SavedSet){setResults(JSON.parse(s.resultsJson));setTab("search");setMessage(`تم فتح المجموعة: ${s.name}`);setTimeout(()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth"}),50)}
  return <main dir="rtl">
    <header className="top"><div><span className="eyebrow">نسخة الجوال المستقلة</span><h1>باحث العقارات</h1><p>ابحث في إعلانات عقار، واحسب العائد والكثافة تلقائيًا.</p></div><div className="topActions"><button className="ghost" onClick={loadSets}>المجموعات المحفوظة</button><button className="ghost" onClick={exportCsv}>تصدير CSV</button></div></header>
    {tab==="saved"?<section className="panel saved"><div className="sectionHead"><div><h2>المجموعات المحفوظة</h2><p>لا تُحفظ النتائج إلا عند ضغط زر الحفظ.</p></div><button className="ghost" onClick={()=>setTab("search")}>العودة للبحث</button></div>{sets.length?sets.map(s=><article className="savedRow" key={s.id}><div><strong>{s.name}</strong><small>{s.propertyType} · {s.count} نتيجة</small></div><div><button onClick={()=>openSet(s)}>فتح</button><button className="danger" onClick={()=>deleteSet(s.id)}>حذف المجموعة</button></div></article>):<div className="empty">لا توجد مجموعات محفوظة بعد.</div>}</section>:<>
    <section className="panel"><div className="sectionHead"><div><h2>مواصفات البحث</h2><p>تُحفظ آخر مواصفات تلقائيًا على هذا الجوال فقط.</p></div><div className="inline"><select defaultValue="" onChange={e=>loadProfile(e.target.value)}><option value="">اختر بحثًا محفوظًا</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="ghost" onClick={saveProfile}>حفظ المواصفات</button><button className="ghost" onClick={clearFields}>مسح الحقول</button></div></div>
      <div className="choiceRow"><label>نوع العقار<select value={filters.propertyType} onChange={e=>update("propertyType",e.target.value)}>{Object.keys(CATEGORIES).map(x=><option key={x}>{x}</option>)}</select></label><fieldset><legend>الغرض</legend><label className="radio"><input type="radio" checked={filters.purpose==="sale"} onChange={()=>update("purpose","sale")}/> بيع</label><label className="radio"><input type="radio" checked={filters.purpose==="rent"} onChange={()=>update("purpose","rent")}/> تأجير</label></fieldset><fieldset><legend>طريقة المطابقة</legend><label className="radio"><input type="radio" checked={filters.mode==="strict"} onChange={()=>update("mode","strict")}/> جميع الشروط</label><label className="radio"><input type="radio" checked={filters.mode==="near"} onChange={()=>update("mode","near")}/> القريبة والناقصة ±50%</label></fieldset></div>
      <h3>المدن والأحياء</h3><div className="locations">{filters.locations.map((l,i)=><div className="location" key={i}><label>المدينة<input value={l.city} onChange={e=>changeLocation(i,"city",e.target.value)} placeholder="مثال: الدمام"/></label><label>الأحياء (بفواصل)<input value={l.neighborhoods.join("، ")} onChange={e=>changeLocation(i,"neighborhoods",e.target.value)} placeholder="اتركها فارغة لكل الأحياء"/></label><button aria-label="حذف المدينة" className="icon danger" onClick={()=>update("locations",filters.locations.filter((_,j)=>j!==i))}>×</button></div>)}</div><button className="add" onClick={addLocation}>+ إضافة مدينة</button>
      <h3>الشروط الرقمية</h3><div className="grid">{nums.map(n=><label key={String(n.key)}>{n.key==="minCount"?countLabel:n.label}<input inputMode="decimal" type="number" min="0" value={String(filters[n.key]||"")} onChange={e=>update(n.key,inputNumber(e.target.value) as never)}/></label>)}</div>
      <h3>البحث في الوصف</h3><label>كلمات مطلوبة (بفواصل)<input value={filters.keywords.join("، ")} onChange={e=>update("keywords",e.target.value.split(/[،,]/).map(x=>x.trim()).filter(Boolean))} placeholder="مثال: مكيفات، مدخل سيارة، صناعات"/><small>يشمل اللواصق مثل: الصناعات، للصناعات، والصناعات.</small></label>
      <div className="limits"><label>عدد الصفحات<input type="number" min="1" max="25" value={filters.maxPages} onChange={e=>update("maxPages",inputNumber(e.target.value))}/></label><label>أقصى إعلانات<input type="number" min="5" max="500" value={filters.maxListings} onChange={e=>update("maxListings",inputNumber(e.target.value))}/></label><span>تُقرأ الصفحات على دفعات معتدلة، وقد يتوقف البحث إذا طلب الموقع تحققًا.</span></div>
      <div className="run"><button className="primary" disabled={busy} onClick={search}>{busy?"جارٍ البحث…":"ابدأ البحث في عقار"}</button><button className="save" disabled={!results.length||busy} onClick={saveResults}>حفظ هذه النتائج</button></div>{busy&&<progress value={progress} max="100"/>}<div className="status">{message}</div>{warnings.length>0&&<details className="warnings"><summary>ملاحظات أثناء القراءة ({warnings.length})</summary>{warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
    </section>
    <Results rows={results} roomMode={ROOM_TYPES.has(filters.propertyType)}/></>}
    <footer>أداة مستقلة · لا تتجاوز تسجيل الدخول أو حماية موقع عقار · البيانات غير المذكورة تبقى «غير مذكور»</footer>
  </main>
}

function Results({rows,roomMode}:{rows:Listing[];roomMode:boolean}){return <section className="panel results" id="results"><div className="sectionHead"><div><span className="eyebrow">النتائج</span><h2>{rows.length} عقار</h2></div><div className="legend"><span className="match">مطابقة</span><span className="near">قريبة</span><span className="missing">ناقصة</span></div></div>{!rows.length?<div className="empty">ستظهر النتائج هنا بعد البحث.</div>:<div className="cards">{rows.map(r=><article className="resultCard" key={r.listingId}><div className="cardTop"><div><span className={`badge ${r.status==="مطابقة"?"match":r.status==="قريبة"?"near":"missing"}`}>{r.status}</span><h3>{r.city||"مدينة غير مذكورة"} · {r.neighborhood||"حي غير مذكور"}</h3><small>رقم الإعلان {r.listingId} · التقييم {r.score}/100</small></div><div className="price">{fmt(r.price)} <small>ر.س</small></div></div><div className="facts"><Fact k="الدخل" v={r.income==null?"غير مذكور":`${fmt(r.income)} ر.س`}/><Fact k="العائد" v={r.yieldPct==null?"غير مذكور":`${fmt(r.yieldPct,2)}%${r.incomeKind==="expected"?" (متوقع)":""}`}/><Fact k="المساحة" v={r.area==null?"غير مذكور":`${fmt(r.area,1)} م²`}/><Fact k="سعر المتر" v={r.sqmPrice==null?"غير مذكور":`${fmt(r.sqmPrice,2)} ر.س`}/><Fact k={roomMode?"الغرف":"الشقق"} v={fmt(roomMode?r.rooms:r.apartments)}/><Fact k="العدادات" v={fmt(r.meters)}/><Fact k="الأدوار" v={fmt(r.floors)}/><Fact k="الشارع" v={r.street==null?"غير مذكور":`${fmt(r.street)} م`}/><Fact k="الكثافة" v={r.density==null?"غير مذكور":`${fmt(r.density,2)} / 100م²`}/><Fact k="العمر" v={r.age||"غير مذكور"}/></div>{roomMode&&r.rooms!=null&&<p className="roomNote">الغرف المذكورة {fmt(r.bedrooms)} + المجالس {r.majlis} + المقالط {r.maqlat}</p>}{r.warnings.length>0&&<details><summary>التحذيرات والبيانات الناقصة</summary><ul>{r.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}<a className="open" href={r.url} target="_blank" rel="noreferrer">فتح الإعلان في عقار ↗</a></article>)}</div>}</section>}
function Fact({k,v}:{k:string;v:string}){return <div><small>{k}</small><strong>{v}</strong></div>}
